name: test

on:
  push:
    branches-ignore:
      - "coverage"
  pull_request:
  workflow_dispatch:
    inputs:
      string_var:
        type: string
        description: 'string variable'
        required: false
        default: 'default string'
      choice_var:
        type: choice
        description: 'choice variable'
        required: false
        default: 'b'
        options:
          - 'a'
          - 'b'
          - 'c'
      boolean_var:
        type: boolean
        description: 'boolean variable'
        required: false
        default: false
      environment_var:
        type: environment
        description: 'enviroment variable'
        required: false
        default: prod
      number_var:
        type: number
        description: 'number variable'
        required: false
        default: 1

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Setup Node
        uses: actions/setup-node@v2
        with:
          node-version: '16'

      - uses: actions/cache@v2
        with:
          path: ~/.npm
          key: node-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            node-

      - name: Install and Build
        run: |
          npm ci
          npm run build
          cp CNAME dist/

      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./dist